<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Seed default record categories.
     *
     * Uses firstOrCreate() so this seeder is idempotent —
     * running it multiple times will never create duplicates.
     */
    public function run(): void
    {
        $categories = [
            'General',
            'HR',
            'Finance',
            'Projects',
            'Legal',
            'IT',
        ];

        foreach ($categories as $name) {
            Category::firstOrCreate(
                ['name' => $name],
                // slug is auto-generated by the Category model's boot() method
            );
        }
    }
}
